### ISSUE TITLE
Infinite Sideline for Events

### ISSUE THREAD

**Issue by baniasbaabe** [mateuszbaransanok/BubbleCV#2]
First of all, thanks for this great project. Really enjoying it. One thing I noticed: Whenever there is a second page (e.g. because of too many events), the line on the left side will go until the bottom, which isn't desirable I guess? Nevertheless, great project

![image](https://github.com/mateuszbaransanok/BubbleCV/assets/72874670/9a6925eb-df3c-4437-88db-fb9764f938b8)

**Comment by mateuszbaransanok** [comment]
I'm glad you like my template :D 
The timeline (black line) was designed to be on every page. I didn't think it was a mistake at first, but I understand that if there is little content on the second page, it looks a little strange.
When I find some time, I will try to fix it.
Thanks for your issue!

**Comment by mateuszbaransanok** [comment]
Hello again!

I have looked into the matter and unfortunately there is no simple solution to this problem. I am using the `background` package to draw the timeline and so far I don't see any other way to do it. 
Especially since recruiters prefer one-page resumes, a better solution is to use the `\cvscale` method to adjust the size of the resume elements to fit on one page.
If you have a lot of information you want to put on your resume, I recommend adjusting the content to a full two pages. This will look much better than a blank half page.

If you still want to achieve your goal, I have prepared a workaround for you. You can simply adjust the height of the timeline on the last page. Feel free to experiment with the code below.


```
\cvsection[languages]{Languages}  %--------------------------------------------------------

\cvskill{English}{Fluent}{1.0}
\cvskill{French}{Intermediate}{0.6}
\cvskill{Russian}{Basic}{0.3}


\end{cv}

\newcommand\cvtimelineheightonlastpage{175}
\SetBgContents{\rule{\cvtimelinewidth mm}{\cvtimelineheightonlastpage mm}}
\SetBgVshift{0.5*\dimexpr(\textheight - \cvtimelineheightonlastpage mm)}
\enlargethispage{\dimexpr(\cvtimelineheightonlastpage mm - \textheight)}

\cvfootnote{
    \tiny I agree to the processing of personal data provided in this document for realizing the recruitment process pursuant to the Personal Data Protection Act of 10 May 2018 (Journal of Laws 2018, item 1000) and in agreement with Regulation (EU) 2016/679 of the European Parliament and of the Council of 27 April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data, and repealing Directive 95/46/EC (General Data Protection Regulation)
}
```
![image](https://github.com/mateuszbaransanok/BubbleCV/assets/58427682/2798e1ad-ca41-4c3f-8b87-f24d2b5d29af)

**Comment by baniasbaabe** [comment]
I think the approach with `cvscale` looks interesting. Is there an example on how you can use this method? Thanks!

**Comment by mateuszbaransanok** [comment]
It is pretty simple, just edit the `bubblecv.sty` file, for eg
```text
%----------------------------------------------------------------------------------------
% CV SCALE
%----------------------------------------------------------------------------------------
\newcommand\cvscale{0.9} 
```

**Comment by baniasbaabe** [comment]
Thanks, I will look into it! :)
